name: NPM License Checker
description: A GitHub action to check 3rd-party licenses
inputs:
  dependencyType:
    description: 'Type of dependencies to include: production | development | all'
    default: all
  startPath:
    description: 'The path of the initial package.json file'
    default: './package.json'
  customFieldsPath:
    description: 'A path to a file to customize the detail output. See: https://www.npmjs.com/package/license-checker#custom-format'
  onlyAllow:
    description: A semicolon-separated list of allowed licenses
    # Based on https://opensource.google/documentation/reference/thirdparty/licenses
    default: AFL-2.1;AFL-3.0;AMPAS;Apache-2.0;Artistic-1.0;Artistic-2.0;Apache-1.1;Beerware;BSL-1.0;BSD-2-Clause;BSD-3-Clause;BSD-2-Clause-Patent;CC-BY-1.0;CC-BY-2.0;CC-BY-2.5;CC-BY-3.0;CC-BY-4.0;JSON;FTL;HPND;ImageMagick;ISC;libtiff;LPL-1.02;MS-PL;MIT;MIT-CMU;NCSA;NIST-Software;OpenSSL;PHP-3.0;PostgreSQL;TCP-wrappers;UPL-1.0;W3C-20150513;WTFPL;Xnet;Zend-2.0;Zlib;ZPL-2.0;
  detailsOutputPath:
    description: The path to output details (e.g. ./licenseData.json).

runs:
  using: 'node20'
  main: 'dist/index.js'