name: 'A11y SLA Breach Labels'
description: 'Automatically applies and updates SLA breach priority labels to accessibility issues based on age and impact.'

inputs:
  token:
    description: 'The GITHUB_TOKEN secret.'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
